name-template: $TAG
tag-template: $TAG
categories:
  - title: '🚀 Novidades (Features)'
    labels: ['feat', 'feature']
  - title: '🐛 Correções (Bug Fixes)'
    labels: ['fix', 'bug']
  - title: '📚 Documentação'
    labels: ['docs', 'documentation']
  - title: '🧰 Manutenção'
    labels: ['chore', 'maintenance']
template: |
  ## O que mudou
  $CHANGES

  **Colaboradores:**
  $CONTRIBUTORS
